### PR TITLE
using startdate to calculate enddate

### PR DESCRIPTION
**Pull request by tracend**
I had a problem using the plugin when the start date was in the future, so the end date that was calculated, based on the current time, appeared to be wrong. 

This small fix addresses this case.

### CODE REVIEW

**Comment by strangerstudios** [comment]
Hmmm. This makes some sense, but there are also sites relying on the old behavior. A common use case for filtering the start date is to add a 30 day trial to a 1 year long membership. Typically, it's intended that the end date remain 1 year from checkout vs 13 months from checkout.

How are you adjusting the start date? Maybe you can accomplish what you need via a filter already in the plugin or one we can add. We have this code in core already that "extends" a membership vs having it end 1 period from checkout if checking out for the same level with an end date:
https://github.com/strangerstudios/paid-memberships-pro/blob/dev/includes/filters.php#L10

We have some similar gists that do this always or for recurring payments as well.

**Comment by tracend** [comment]
My use case is a bit different. 

To be specific, this site is for joining training sessions that run in weekly intervals. So if you sign up online any day of the week you will be bumped to the next session on a specific day of the week. 

In this case the end date (after a set number of weeks) needs to be calculated based on the start date, not the purchase date. 

Any help how to achieve this with the existing plugin appreciated.

**Comment by strangerstudios** [comment]
I added a new filter pmpro_checkout_end_date that works similar to the pmpro_checkout_start_date filter. This will go out in 1.8.9 today. There was a way to do this using the pmpro_checkout_level filter to basically change the expiration from 1 week to however many days it is until next next Monday, but this is cleaner.
https://github.com/strangerstudios/paid-memberships-pro/commit/0ef1925b2aae67d7e11eeefd82fb73f39171221e

And here is an example using similar to what you need I think:
https://gist.github.com/strangerstudios/d2e1144158f840fceaba5bbbad5f01fc

**Comment by tracend** [comment]
Looks good. Thanks for addressing this. Feel free to close this pull request when ready.

**Pull request closed without merging**
