### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by AiratHalitov**
README.md is more useful for GitHub than readme.txt
You can see screenshots and good markup. 

And this is will better for SEO of github repository.

### CODE REVIEW

**Comment by AiratHalitov** [comment]
Can anyone approve this PR?

**Comment by eighty20results** [comment]
Hi,

See #131 where Jason explains the rationale for not having a .md file.

**Comment by AiratHalitov** [comment]
@eighty20results
But GitHub repo should have README.md file. 
And as you can see my version of README.md is good and useful. 
I don't going to delete readme.txt. 
Here will be two files: readme.txt for wordpress and README.md for GitHub.

**Comment by AiratHalitov** [comment]
@eighty20results 
Can you check my new README.md file? 
Now you can use it without any updates. 
I deleted full changelog (link to file instead), replaced HTTP to HTTPS (in website links) and added contributing guideline.
If you have any suggestions, I can add them to the file.

**Comment by AiratHalitov** [comment]
@andrewlimaza can you check this PR?

**Pull request closed without merging**
