### PR TITLE
Replace jQuery deprecated shorthands with generic handler and trigger

### LINKED ISSUE #1974: Update old jQuery syntax
Your jQuery code is still using old deprecated jQuery syntax in many places. Some examples:

`click(...)` instead of `on('click',...)`:
https://github.com/strangerstudios/paid-memberships-pro/blob/4812f157e759a38b2d22cf56be728cc00592af07/js/pmpro-checkout.js#L29

`change(...)` instead of `on('change',...)`:
https://github.com/strangerstudios/paid-memberships-pro/blob/1504409e7833f9304922b828b22249a1b625cb28/includes/profile.php#L102

`$( document ).ready(function()` instead of `$(function()` (link: https://api.jquery.com/ready/):
https://github.com/strangerstudios/paid-memberships-pro/blob/38c18597d4b0eee457d777f67c3223a9b42e28b4/js/pmpro-admin.js#L45

This old syntax still works (with warnings) in the latest version of jQuery (3.6.0) but might be removed in future versions of the library, so it's recommended to update it.

### PR DESCRIPTION
**Pull request by mircobabini**
### All Submissions:

* [x] Have you followed the [Contributing guideline](https://github.com/strangerstudios/paid-memberships-pro/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/strangerstudios/paid-memberships-pro/pulls) for the same update/change?

### Changes proposed in this Pull Request:

jQuery shorthands (.click(), .submit(), ...) are deprecated since jQuery 3.0+. WordPress 5.6 bundles jQuery 3.5.1, WordPress 5.9 bundles jQuery 3.6.0. Replacing shorthands is safe.

Conversion strategy https://www.drupal.org/project/webform/issues/3187940#comment-13944348

Resolves #1974.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Replace jQuery deprecated shorthands with generic handler and trigger

### CODE REVIEW

**Comment by andrewlimaza** [comment]
These shorthands have been deprecated in jQuery Migrate V3.0+ -> https://github.com/jquery/jquery-migrate/blob/main/warnings.md#jqmigrate-jqueryfnclick-event-shorthand-is-deprecated

**Comment by andrewlimaza** [comment]
@mircobabini this just needs merge conflicts to be resolved (seems like a straight forward change from shorthand to using 'on' instead which seems fine to me).

**Comment by mircobabini** [comment]
> @mircobabini this just needs merge conflicts to be resolved (seems like a straight forward change from shorthand to using 'on' instead which seems fine to me).

Yeah, I can handle this. Gonna hit you up as soon as done.

**Comment by mircobabini** [comment]
Done, ready to be reviewed.

**Comment by dparker1005** [comment]
Closed in favor of #2859

**Pull request closed without merging**
