### PR TITLE
Change PayPal button to the new HTML version

### PR DESCRIPTION
**Pull request by mircobabini**
### All Submissions:

* [x] Have you followed the [Contributing guideline](https://github.com/strangerstudios/paid-memberships-pro/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/strangerstudios/paid-memberships-pro/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This is useful to
- have the minimum ui switch as possibile once we will upgrade to PayPal Payments
- enable i18n for "Check Out with" string

Thanks to https://developer.paypal.com/docs/checkout/standard/#link-howitworks stye guide, we can have a nice looking PayPal yellow button with i18n.

It has been done by keeping the old image (hidden) to be used as the submit button, once clicked on the html one (which is into a `<label>` tag, connected to the submit image).

Spreaded to PayPal, PayPal Standard and PayPal Express. CSS prefixed.

Screenshot 2022-05-09 at 23 45 39

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by dparker1005 — APPROVED** [review]

**Comment by andrewlimaza** [comment]
The styling is out for me

Screen Shot 2022-06-23 at 13 29 06

**Comment by mircobabini** [comment]
Gonna double check this.

**Comment by kimcoleman** [comment]
Worked on a variation of the approach here - https://github.com/strangerstudios/paid-memberships-pro/pull/3026. This feels like the direction we should take now to control this button. Let me know your thoughts - if we go with the new one we can close this one.

**Comment by dparker1005** [comment]
Closing in favor of #3026

**Pull request closed without merging**
