### PR TITLE
Memberlist Export Joindate produces same result as table

### PR DESCRIPTION
**Pull request by JarrydLong**
### All Submissions:

* [x] Have you followed the [Contributing guideline](https://github.com/strangerstudios/paid-memberships-pro/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/strangerstudios/paid-memberships-pro/pulls) for the same update/change?

### Changes proposed in this Pull Request:

In the export we reference the joindate `array_push($csvoutput, pmpro_enclose(date_i18n($dateformat, $theuser->user_registered)));` While in the table we reference `user_registered` 

I've tested an export with referencing $theuser->user_registered and we get the same results that the user sees in the table.

This issue came up on a customer's site where I suspect they had some users imported. 

The start date showed fine in the table but gave a 1970 date when exporting. 

### How to test the changes in this Pull Request:

1. Export a member list as normal from the Members tab. 
2. As mentioned above though, this issue was experienced on a customer site with the possibility of users who were imported - making this change just produced the same results in the export as one sees in the member list table.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

Member list export join date now references the user_registration date in an export

### CODE REVIEW

**Comment by ideadude** [comment]
Maybe the heading is wrong instead?

**Comment by dparker1005** [comment]
After digging into this more, the members list has both "registered" and "start date", whereas the CSV export only has "joined".

We should update the CSV to have both "registered" and "start_date" to mirror the members list.

**Review by dparker1005 — CHANGES_REQUESTED** [review]
After digging into this more, the members list has both "registered" and "start date", whereas the CSV export only has "joined".

We should update the CSV to have both "registered" and "start_date" to mirror the members list.

**Comment by JarrydLong** [comment]
We haven't been able to replicate the original issue that spurred this PR on - closing this for now - if it becomes an issue in the future we can relook at it.

**Pull request closed without merging**
