### PR TITLE
Formatting

### PR DESCRIPTION
**Pull request by meths**
There were a mix of formats so not sure on your preferred line endings.  Ignore if you develop on Windows.

This patch comes from running dos2unix and then removing trailing white space from the entire tree.  This makes collaboration easier when people don't have to worry about conflicting whitespace.

### CODE REVIEW

**Comment by strangerstudios** [comment]
I agree this is a good idea, but also takes a lot of trust to accept a commit that changes almost every line. I'll have to go through this or maybe run the same scripts myself and upload.

**Comment by meths** [comment]
Of course, that's understandable.  The commands run were:
find . -type f -name "*.html" -print0 | xargs -0 dos2unix
find . -type f -name "*.php" -print0 | xargs -0 dos2unix
find . -type f -name "*.txt" -print0 | xargs -0 dos2unix
find . -type f -name "*.js" -print0 | xargs -0 dos2unix
find . -type f -name "*.css" -print0 | xargs -0 dos2unix
That makes sure you don't break images or language files just running it on all.

Then the same for the whitespace:
find . -type f -name "*.php" -print0 | xargs -0 sed -i '' -E "s/[[:blank:]]+$//"
find . -type f -name "*.txt" -print0 | xargs -0 sed -i '' -E "s/[[:blank:]]+$//"
find . -type f -name "*.css" -print0 | xargs -0 sed -i '' -E "s/[[:blank:]]+$//"
find . -type f -name "*.js" -print0 | xargs -0 sed -i '' -E "s/[[:blank:]]+$//"
find . -type f -name "*.html" -print0 | xargs -0 sed -i '' -E "s/[[:blank:]]+$//"

**Comment by strangerstudios** [comment]
Thanks for those. I'm having trouble running those in my environment (CENTOS 6) but will definitely look into this.

**Comment by meths** [comment]
Oh, if you just copied them it's probably because github formatting lost the asterisks in the -name parameters.  Sorry, I've just noticed that.
Anyway, thanks for looking in to this.

**Comment by strangerstudios** [comment]
I've done this. Here are the commands I ran. The sed/whitespace command I used is different from yours.
https://gist.github.com/strangerstudios/8735bbef9fd03469129a

Here are the commits:
https://github.com/strangerstudios/paid-memberships-pro/commit/3b61db5b30d0dfc542a25e0f7c82e904e5852668
https://github.com/strangerstudios/paid-memberships-pro/commit/a5c14923b6d28af43c8fc846ef9f0b911e1fd613
https://github.com/strangerstudios/paid-memberships-pro/commit/8d7d23c179270555ec790fa11b00181b7b813aba
https://github.com/strangerstudios/paid-memberships-pro/commit/8838197501d8bcd83caf921f6b0130cf2a17af76
https://github.com/strangerstudios/paid-memberships-pro/commit/5f855a434fc622321d6548b092a2afd647cff236
https://github.com/strangerstudios/paid-memberships-pro/commit/d3910cb70e0f6ff4f1593d6adadcb4e5cbfcdae4
https://github.com/strangerstudios/paid-memberships-pro/commit/a72f6000b1a12f165fc35979a2c8d833fa5e5407
https://github.com/strangerstudios/paid-memberships-pro/commit/bdf6dcc1fd0a58b5b0e024dc0672b5f55f5b528a

**Pull request closed without merging**
