### PR TITLE
Trims spacing on dropdown values to ensure consistent results

### PR DESCRIPTION
**Pull request by JarrydLong**
### All Submissions:

* [x] Have you followed the [Contributing guideline](https://github.com/strangerstudios/paid-memberships-pro/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/strangerstudios/paid-memberships-pro/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Trims spacing around a dropdown's values so that checks validate when the value is selected

### How to test the changes in this Pull Request:

1. Create a dropdown field in User fields
2. set the values to have a space after each of them (normal whitespace)
3. Edit the profile using the fronend profile edit page. Choose a new value from the dropdown and save. It saves correctly as before - but it should show the correct/selected field from the dropdown.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

Trims whitespace from dropdown values

### CODE REVIEW

**Comment by ideadude** [comment]
Good idea. Is there any chance this breaks things for users who chose values on old fields with the extra space? Can we test that?

1. Use the non-patched version of PMPro.
2. Create a select field with 2 options, values "a " and "b " (note spaces).
3. Have the user select option "b " and save from the edit user or profile page.
4. Apply the patch. Visit the edit user or profile page.
5. Is "b " still selected for them?

We could potentially trim things going into the `selected()` calls and/or update some other code to make sure old values get checked correctly.

I think it's possible that " " at the front or back is important. Choose your separator: , or / or | or " " LOL But I think that should be a rare enough edge case to ignore. However if a site was set up and recorded everyone's city as "New York City ", after this update, I'm worried that data appears to be lost to admins and users.

**Comment by JarrydLong** [comment]
Just making a note here that trimming only really happens on the selected function to show if selected, so if you have 1000 users with the space it 'should' fix itself the next time you view/edit your profile and then save

**Comment by ideadude** [comment]
What Jarryd says makes sense. We still need to test. After testing, let's merge.

**Review by dparker1005 — CHANGES_REQUESTED** [review]
Just tested and the change works nicely for `select` field. In the current dev branch, if a user chose an option with whitespace, it would save in the database without the white space and fields would not default to their selected option when displayed again. After this PR, those selections are recovered nicely and show what the user selected, even if the original selection was before this PR was implemented.

I am requesting changes because other fields still run into the same problem for options with whitespace. Specifically, I tested with select2. I assume that the fix is similar, but it should be tested with all field types that use options.

**Pull request merged**
