### PR TITLE
Sales Report: push Revenue label right and align vertical

### PR DESCRIPTION
**Pull request by mircobabini**
### All Submissions:

* [x] Have you followed the [Contributing guideline](https://github.com/strangerstudios/paid-memberships-pro/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/strangerstudios/paid-memberships-pro/pulls) for the same update/change?

### Changes proposed in this Pull Request:
Screenshot 2022-05-09 at 21 24 05

This is the "Sales" report. Not looking good because with i18n (italian in that case) some rows height is double.
This PR aims to:
- right align "Revenue" label in table head
- vertical align table values

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by andrewlimaza** [comment]
@mircobabini could you please provide a screenshot of after implementing this fix?

**Comment by mircobabini** [comment]
Sure thing.

## Before
Screenshot 2022-05-11 at 10 16 52

## After
Screenshot 2022-05-11 at 10 17 20

**Review by andrewlimaza — APPROVED** [review]

**Comment by andrewlimaza** [comment]
Thanks look good! :)

**Comment by kimcoleman** [comment]
This is splitting hairs, but while I do approve of the right align th for "Revenue" (last column) but I prefer the vertical align top. It is read left to right (for LTR languages) and the flow feels that it makes more sense to me that you read across the headings. There are many combinations of how text could wrap here and in some places one looks better than the other. 

Screen Shot 2022-05-11 at 8 57 29 AM

Screen Shot 2022-05-11 at 8 56 50 AM

My vote is vertical align top.

**Comment by andrewlimaza** [comment]
@kimcoleman changed it to `vertical-align: top;` instead. Overlooked the other reports and they're aligned top as well, so let's keep it like this for now.

**Pull request merged**
