### PR TITLE
Tweak: Add more filters

### PR DESCRIPTION
**Pull request by louiswol94**
This will help users tremendously for better integration with https://wordpress.org/plugins/pmpro-multiple-currencies/

### CODE REVIEW

**Comment by louiswol94** [comment]
@ideadude @kimcoleman Please review :-)

**Comment by louiswol94** [comment]
@MaximilianoRicoTabo any chance you can review this PR?

**Comment by louiswol94** [comment]
@mircobabini any chance you can review this PR?

(Sorry for all the comments guys, this will be the last one, I promise).

Really hoping to get this merged 🤞

**Comment by dparker1005** [comment]
Hi @louiswol94,

Thank you for submitting these changes.

While the filters in this PR will help adjust the formatting in the specific places you mentioned, I believe this is a good opportunity to abstract how order values are formatted across PMPro. I have opened an alternative PR with additional filters that I think will address the issues you’re encountering: https://github.com/strangerstudios/paid-memberships-pro/pull/3009

Please let me know if the changes in that PR are sufficient for your use case. If you have any concerns about those changes, feel free to let me know, and we can discuss further.

**Comment by louiswol94** [comment]
> Hi @louiswol94,
> 
> Thank you for submitting these changes.
> 
> While the filters in this PR will help adjust the formatting in the specific places you mentioned, I believe this is a good opportunity to abstract how order values are formatted across PMPro. I have opened an alternative PR with additional filters that I think will address the issues you’re encountering: #3009
> 
> Please let me know if the changes in that PR are sufficient for your use case. If you have any concerns about those changes, feel free to let me know, and we can discuss further.

Hey @dparker1005, thank you for the response. I agree it is a better approach and easier to maintain!

As long as we can have access to the order's data in the callback function then I'm good to go mate.

Thanks!

**Comment by dparker1005** [comment]
Hi @louiswol94, thank you for taking a look at that new PR! As it sounds like those new filters will be sufficient for your use-case, I am going to close this PR. If you would ever like to discuss these filters again, please open a new PR and we can discuss further there.

**Pull request closed without merging**
