### PR TITLE
BUG: Cancellations showing 0 for All Time under Membership report

### PR DESCRIPTION
**Pull request by contemplate**
The last bug fix didn't actually fix the issue.  This fixes it for realz!

### CODE REVIEW

**Comment by strangerstudios** [comment]
Thanks for the pull request! I think we can merge it as is, but had a question at one point: https://github.com/strangerstudios/paid-memberships-pro/pull/418/files#r96014772

**Comment by contemplate** [comment]
Great! Maybe I'm missing something.  What is the question? :)

**Comment by strangerstudios** [comment]
There was a line in the query that you removed:

    $sqlQuery .= "AND mu2.id IS NULL 

This the query left joins onto mu2 and checks to see if the user with an entry with status "cancelled"/etc has a newer entry with status "active" that was created within 24 hours of the cancellation... basically showing that the user upgraded/downgraded instead of cancelled.

This isn't really necessary anymore since we have specific admin_changed and changed status for when this happens, but older sites (before 2015 or so) will have users who upgraded and would be counted as cancels without this. That might be okay.

If this is confusing to you, I'll noodle that over and add it back in or keep it out and merge the rest of your fixes.

**Comment by contemplate** [comment]
Actually that exact line directly fixed the Zero cancellations issue on two site we built in 2015 & 2016.  I remember months ago when I was debugging this and manually running this query through PHPMYADMIN with user ids I know that should show up as cancelled that it was produce no results.  I removed that and it showed the correct results.  I hadn't thought about the situation you are describing.

**Comment by strangerstudios** [comment]
I'm going to merge this in with the reverse compatibility stuff out. I'll also remove the related left join in the query. Thanks!

**Pull request merged**
