### PR TITLE
Change status to receive new membership information

### PR DESCRIPTION
**Pull request by andrewlimaza**
ENHANCEMENT: Add more membership statuses to trigger on when polling for membership information. This is useful for Zapier Application to trigger on more than just active accounts. This will help with cancelled and expired level changes too.

### All Submissions:

* [x] Have you followed the [Contributing guideline](https://github.com/strangerstudios/paid-memberships-pro/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/strangerstudios/paid-memberships-pro/pulls) for the same update/change?

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Lets add a new REST API parameter to support choosing which status to filter by (one comma separated list). We can default to showing these that you've set, but it would be good to allow to show only active.

**Review by sc0ttkclark — CHANGES_REQUESTED** [review]
Let's make this filterable via REST API param, default can be these new statuses, but someone may want to just filter by active.

**Comment by andrewlimaza** [comment]
I've made the changes to support the parameter 'level_status' which can take single or comma-separated values.

I also added in the filter 'pmpro_rest_recent_member_default_level_status' should you not be able to add in a parameter during the request (PMPro Zapier application doesn't support params for the trigger that runs on this route). I will look at adding this in the future to PMPro Zapier application when triggering data on this event.

Let me know your thoughts. Will move it to draft too for the time being.

**Comment by andrewlimaza** [comment]
I've made the decision to keep backwards compatibility. This route is used solely by the Paid Memberships Pro - Zapier application.

This defaults to standard functionality of 'active' membership statuses only, unless the level_status parameter is supplied. An update will be coming to the Zapier Application to support input and support this parameter in a future release. This will keep current zaps running on Zapier 1.0.0 unaltered as there's quite a lot of data being run through PMPro Zapier Application.

I've left it as a draft for now, but I'm happy with this. Let me know your thoughts.

**Review by sc0ttkclark — APPROVED** [review]

**Pull request merged**
