### PR TITLE
Warning Message for enabling recurring and expiration

### PR DESCRIPTION
**Pull request by andrewlimaza**
Show a pop-up alert when a user selects both

### CODE REVIEW

**Comment by eighty20results** [comment]
Wouldn't it make sense to stay consistent with how we message/notify on the admin pages?

Everywhere else, we set the pmpro_msg/pmpro_msgt, but now we're suddenly starting to throw modal pop-ups (which quickly become annoying).

**Comment by andrewlimaza** [comment]
maybe.

**Comment by andrewlimaza** [comment]
Can probably do away with the popup and just show the warning text below the 'expiration settings'. This way it is way more clear and shows as the user selects the checkbox.

**Comment by andrewlimaza** [comment]
I removed the code for the `alert`

**Comment by andrewlimaza** [comment]
Resubmitting a new PR for this.

**Pull request closed without merging**
