### PR TITLE
Fixed issue with membership cancellation

### PR DESCRIPTION
**Pull request by rsm0128**
SQL query to get the latest order for a user was incorrect and it caused an issue with refund.

### CODE REVIEW

**Comment by rsm0128** [comment]
```
		$other_order_ids = $wpdb->get_col(
			"SELECT id, IF(subscription_transaction_id = '', CONCAT('UNIQUE_SUB_ID_', id), subscription_transaction_id) as unique_sub_id
											FROM $wpdb->pmpro_membership_orders
											WHERE user_id = '" . esc_sql( $user_id ) . "'
												AND status = 'success'
											GROUP BY unique_sub_id
											ORDER BY id DESC"
		);
```
We need to use group function Max instead of `ORDER BY id DESC`

**Comment by andrewlimaza** [comment]
@rsm0128 What was the issue with the refund? Did it refund the wrong order/subscription?

Please let me know how I can replicate this on PMPro's side so we can thoroughly test it.

**Comment by rsm0128** [comment]
@andrewlimaza `GROUP BY unique_sub_id` groups orders and we select `id`. But it returns random order id in the group not the latest order id.
`ORDER BY id DESC` is not necessary here. We should use `MAX(id)`

**Comment by rsm0128** [comment]
@andrewlimaza Any update on this?

**Comment by dparker1005** [comment]
Hi @rsm0128,

In PMPro v3.0, the logic for terminating subscriptions associated with cancelled memberships was overhauled to use the new `PMPro_Subscriptions`.  This eliminated the query that this PR modified. 

Can you please confirm that this issue is resolved in PMPro v3.0+?

**Comment by dparker1005** [comment]
I am closing this PR as it should not still be an issue in PMPro v3.0. If this is still an issue that you are seeing on your website, please open a new PR/Issue and we can look into this behavior further there

**Pull request closed without merging**
